[package]
name = "dynamic_wallpaper"
version = "0.1.0"
authors = ["Matthew Klein <mklein994@gmail.com>"]
edition = "2018"

[badges]
travis-ci = { repository = "mklein994/dynamic_wallpaper" }
maintenance = { status = "experimental" }

[dependencies]
chrono = { version = "0.4.6", features = ["serde"] }
dirs = "2.0.1"
serde = { version = "1.0.105", features = ["derive"] }
sunrise = { git = "https://github.com/mklein994/rust-sunrise" }
toml = "0.5.1"

[dev-dependencies]
lazy_static = "1.2.0"
