[package]
name = "dynamic_wallpaper"
version = "0.1.0"
authors = ["Matthew Klein <mklein994@gmail.com>"]
edition = "2018"

[badges]
travis-ci = { repository = "mklein994/dynamic_wallpaper" }
maintenance = { status = "experimental" }

[dependencies]
chrono = { version = "0.4.6", features = ["serde"] }
chrono-humanize = "0.0.11"
dirs = "2.0.1"
env_logger = "0.6.0"
log = "0.4.6"
serde = "1.0.80"
serde_derive = "1.0.80"
spa = "0.2.0"
toml = "0.5.1"

[dev-dependencies]
lazy_static = "1.2.0"
